DROP TABLE IF EXISTS animal_dim_info;
CREATE TABLE animal_dim_info(
   ANIMAL_DIM_KEY SERIAL PRIMARY KEY,
   ANIMAL_ID VARCHAR,
   ANIMAL_TYPE VARCHAR,
   ANIMAL_NAME VARCHAR,
   DOB DATE,
   BREED VARCHAR,
   COLOR VARCHAR,
   REPROD VARCHAR,
   GENDER VARCHAR,
   TIMESTMP TIMESTAMP
);

DROP TABLE IF EXISTS outcome_dim;
CREATE TABLE outcome_dim(
   OUTCOME_DIM_KEY SERIAL PRIMARY KEY,
   OUTCOME_TYPE VARCHAR,
   OUTCOME_SUBTYPE VARCHAR
);


DROP TABLE IF EXISTS timing_dim;
CREATE TABLE timing_dim(
   TIME_DIM_KEY SERIAL PRIMARY KEY,
   MONTHH VARCHAR,
   YEARR INT
);



DROP TABLE IF EXISTS outcome_fact;
CREATE TABLE outcome_fact(
   OUTCOMESFACT_KEY SERIAL PRIMARY KEY,
   OUTCOME_DIM_KEY INT REFERENCES outcome_dim(OUTCOME_DIM_KEY),
   ANIMAL_DIM_KEY INT REFERENCES animal_dim_info(ANIMAL_DIM_KEY),
   TIME_DIM_KEY INT REFERENCES timing_dim(TIME_DIM_KEY)
);

DROP TABLE IF EXISTS temp_table;
CREATE TABLE temp_table(
   TEMP_KEY SERIAL PRIMARY KEY,
   ANIMAL_ID VARCHAR,
   ANIMAL_TYPE VARCHAR,
   ANIMAL_NAME VARCHAR,
   DOB DATE,
   BREED VARCHAR,
   COLOR VARCHAR,
   REPROD VARCHAR,
   GENDER VARCHAR,
   TIMESTMP TIMESTAMP,
   MONTHH VARCHAR,
   YEARR INT,
   OUTCOME_TYPE VARCHAR,
   OUTCOME_SUBTYPE VARCHAR
);